# Generated by Django 4.2.11 on 2024-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierecord',
            old_name='moviname',
            new_name='moviename',
        ),
        migrations.AlterField(
            model_name='movierecord',
            name='moviedate',
            field=models.CharField(max_length=10),
        ),
    ]
