# Generated by Django 4.2.11 on 2024-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_moviname_movierecord_moviename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('moviename', models.CharField(max_length=255)),
                ('movieyear', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=50)),
            ],
        ),
    ]
