# Generated by Django 4.2.11 on 2024-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_finaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldata',
            name='seats',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
