# Generated by Django 4.2.11 on 2024-04-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_finaldata_date_finaldata_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaldata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='finaldata',
            name='time',
        ),
    ]
